// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: msggateway.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AgentUserJoinSessionMsg;
@class CreateSessionMsg;
@class EndSessionMsg;
@class HasReadReceiptMsg;
@class Join;
@class MsgBody;
@class SessionBasic;
@class State;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum MsgType

typedef GPB_ENUM(MsgType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  MsgType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  MsgType_JoinServer = 0,
  MsgType_TextMsgType = 1,
  MsgType_ImgMsgType = 2,
  MsgType_VideoMsgType = 3,
  MsgType_CreateSessionMsgType = 4,

  /** 客服接入推送 */
  MsgType_AgentUserJoinSessionMsgType = 5,

  /** 已读推送 */
  MsgType_HasReadReceiptMsgType = 6,

  /** 用户已经被服务器踢出 */
  MsgType_KickOffLineMsgType = 7,

  /** faq(contentType) */
  MsgType_FaqMsgType = 8,

  /** 知识点(contentType) */
  MsgType_KnowledgePointMsgType = 9,

  /** 答案(contentType) */
  MsgType_KnowledgeAnswerMsgType = 10,

  /** 会话结束 */
  MsgType_EndSessionMsgType = 11,
};

GPBEnumDescriptor *MsgType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MsgType_IsValidValue(int32_t value);

#pragma mark - MsggatewayRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface MsggatewayRoot : GPBRootObject
@end

#pragma mark - State

typedef GPB_ENUM(State_FieldNumber) {
  State_FieldNumber_Code = 1,
  State_FieldNumber_Message = 2,
};

GPB_FINAL @interface State : GPBMessage

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

#pragma mark - MsgEntityToServer

typedef GPB_ENUM(MsgEntityToServer_FieldNumber) {
  MsgEntityToServer_FieldNumber_MsgType = 1,
  MsgEntityToServer_FieldNumber_Seq = 2,
  MsgEntityToServer_FieldNumber_Join = 3,
  MsgEntityToServer_FieldNumber_MsgBody = 4,
};

GPB_FINAL @interface MsgEntityToServer : GPBMessage

@property(nonatomic, readwrite) MsgType msgType;

@property(nonatomic, readwrite) int64_t seq;

@property(nonatomic, readwrite, strong, null_resettable) Join *join;
/** Test to see if @c join has been set. */
@property(nonatomic, readwrite) BOOL hasJoin;

@property(nonatomic, readwrite, strong, null_resettable) MsgBody *msgBody;
/** Test to see if @c msgBody has been set. */
@property(nonatomic, readwrite) BOOL hasMsgBody;

@end

/**
 * Fetches the raw value of a @c MsgEntityToServer's @c msgType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t MsgEntityToServer_MsgType_RawValue(MsgEntityToServer *message);
/**
 * Sets the raw value of an @c MsgEntityToServer's @c msgType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetMsgEntityToServer_MsgType_RawValue(MsgEntityToServer *message, int32_t value);

#pragma mark - MsgEntityToFrontEnd

typedef GPB_ENUM(MsgEntityToFrontEnd_FieldNumber) {
  MsgEntityToFrontEnd_FieldNumber_MsgType = 1,
  MsgEntityToFrontEnd_FieldNumber_State = 2,
  MsgEntityToFrontEnd_FieldNumber_MsgBody = 3,
  MsgEntityToFrontEnd_FieldNumber_CreateSessionMsg = 4,
  MsgEntityToFrontEnd_FieldNumber_AgentUserJoinSessionMsg = 5,
  MsgEntityToFrontEnd_FieldNumber_HasReadReceiptMsg = 6,
  MsgEntityToFrontEnd_FieldNumber_EndSessionMsg = 7,
};

GPB_FINAL @interface MsgEntityToFrontEnd : GPBMessage

@property(nonatomic, readwrite) MsgType msgType;

@property(nonatomic, readwrite, strong, null_resettable) State *state;
/** Test to see if @c state has been set. */
@property(nonatomic, readwrite) BOOL hasState;

@property(nonatomic, readwrite, strong, null_resettable) MsgBody *msgBody;
/** Test to see if @c msgBody has been set. */
@property(nonatomic, readwrite) BOOL hasMsgBody;

@property(nonatomic, readwrite, strong, null_resettable) CreateSessionMsg *createSessionMsg;
/** Test to see if @c createSessionMsg has been set. */
@property(nonatomic, readwrite) BOOL hasCreateSessionMsg;

@property(nonatomic, readwrite, strong, null_resettable) AgentUserJoinSessionMsg *agentUserJoinSessionMsg;
/** Test to see if @c agentUserJoinSessionMsg has been set. */
@property(nonatomic, readwrite) BOOL hasAgentUserJoinSessionMsg;

@property(nonatomic, readwrite, strong, null_resettable) HasReadReceiptMsg *hasReadReceiptMsg;
/** Test to see if @c hasReadReceiptMsg has been set. */
@property(nonatomic, readwrite) BOOL hasHasReadReceiptMsg;

@property(nonatomic, readwrite, strong, null_resettable) EndSessionMsg *endSessionMsg;
/** Test to see if @c endSessionMsg has been set. */
@property(nonatomic, readwrite) BOOL hasEndSessionMsg;

@end

/**
 * Fetches the raw value of a @c MsgEntityToFrontEnd's @c msgType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t MsgEntityToFrontEnd_MsgType_RawValue(MsgEntityToFrontEnd *message);
/**
 * Sets the raw value of an @c MsgEntityToFrontEnd's @c msgType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetMsgEntityToFrontEnd_MsgType_RawValue(MsgEntityToFrontEnd *message, int32_t value);

#pragma mark - Join

typedef GPB_ENUM(Join_FieldNumber) {
  Join_FieldNumber_Uid = 1,
  Join_FieldNumber_SessionId = 2,
  Join_FieldNumber_Token = 3,
};

GPB_FINAL @interface Join : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@end

#pragma mark - JoinResp

typedef GPB_ENUM(JoinResp_FieldNumber) {
  JoinResp_FieldNumber_SessionId = 1,
  JoinResp_FieldNumber_ServerId = 2,
};

GPB_FINAL @interface JoinResp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *serverId;

@end

#pragma mark - MsgBody

typedef GPB_ENUM(MsgBody_FieldNumber) {
  MsgBody_FieldNumber_SenderUid = 1,
  MsgBody_FieldNumber_ReceiverUid = 2,
  MsgBody_FieldNumber_MsgType = 3,
  MsgBody_FieldNumber_MsgSeq = 4,
  MsgBody_FieldNumber_EncKey = 5,
  MsgBody_FieldNumber_MsgBody = 6,
  MsgBody_FieldNumber_Status = 7,
  MsgBody_FieldNumber_CreateTime = 8,
  MsgBody_FieldNumber_ClientMsgId = 9,
  MsgBody_FieldNumber_SessionId = 10,
  MsgBody_FieldNumber_SendTime = 11,
};

GPB_FINAL @interface MsgBody : GPBMessage

/** 发送者ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *senderUid;

/** 接收者ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *receiverUid;

/** 消息类型 */
@property(nonatomic, readwrite) MsgType msgType;

/** 当前消息序列号 */
@property(nonatomic, readwrite) int32_t msgSeq;

/** 消息解密Key */
@property(nonatomic, readwrite, copy, null_resettable) NSString *encKey;

/** 消息体内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgBody;

/** 0-未读， 1-已读 */
@property(nonatomic, readwrite) int32_t status;

/** 消息创建时间 */
@property(nonatomic, readwrite) int64_t createTime;

/** 客户端自定义消息ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *clientMsgId;

/** sessionId */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

/** 客户端创建的发送时间 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sendTime;

@end

/**
 * Fetches the raw value of a @c MsgBody's @c msgType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t MsgBody_MsgType_RawValue(MsgBody *message);
/**
 * Sets the raw value of an @c MsgBody's @c msgType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetMsgBody_MsgType_RawValue(MsgBody *message, int32_t value);

#pragma mark - SessionBasic

typedef GPB_ENUM(SessionBasic_FieldNumber) {
  SessionBasic_FieldNumber_SessionId = 1,
  SessionBasic_FieldNumber_HeadIcon = 2,
  SessionBasic_FieldNumber_Uid = 3,
  SessionBasic_FieldNumber_Source = 4,
  SessionBasic_FieldNumber_NickName = 5,
  SessionBasic_FieldNumber_DevNo = 6,
  SessionBasic_FieldNumber_CreateTime = 7,
  SessionBasic_FieldNumber_Language = 8,
  SessionBasic_FieldNumber_Extra = 9,
  SessionBasic_FieldNumber_LatestMsg = 10,
};

GPB_FINAL @interface SessionBasic : GPBMessage

/** 会话ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

/** 头标ICon */
@property(nonatomic, readwrite, copy, null_resettable) NSString *headIcon;

/** uid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 来源APP */
@property(nonatomic, readwrite, copy, null_resettable) NSString *source;

/** 简称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickName;

/** 设备号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *devNo;

/** 创建时间 */
@property(nonatomic, readwrite) int64_t createTime;

/** 接入语言 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *language;

/** 额外保留信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extra;

/** 最新消息 */
@property(nonatomic, readwrite, strong, null_resettable) MsgBody *latestMsg;
/** Test to see if @c latestMsg has been set. */
@property(nonatomic, readwrite) BOOL hasLatestMsg;

@end

#pragma mark - CreateSessionMsg

typedef GPB_ENUM(CreateSessionMsg_FieldNumber) {
  CreateSessionMsg_FieldNumber_SessionBasic = 1,
};

GPB_FINAL @interface CreateSessionMsg : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) SessionBasic *sessionBasic;
/** Test to see if @c sessionBasic has been set. */
@property(nonatomic, readwrite) BOOL hasSessionBasic;

@end

#pragma mark - AgentUserJoinSessionMsg

typedef GPB_ENUM(AgentUserJoinSessionMsg_FieldNumber) {
  AgentUserJoinSessionMsg_FieldNumber_Username = 1,
};

GPB_FINAL @interface AgentUserJoinSessionMsg : GPBMessage

/** 客服用户名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@end

#pragma mark - HasReadReceiptMsg

typedef GPB_ENUM(HasReadReceiptMsg_FieldNumber) {
  HasReadReceiptMsg_FieldNumber_SessionId = 1,
  HasReadReceiptMsg_FieldNumber_HasReadSeqsArray = 2,
};

GPB_FINAL @interface HasReadReceiptMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *hasReadSeqsArray;
/** The number of items in @c hasReadSeqsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger hasReadSeqsArray_Count;

@end

#pragma mark - KickOffLineMsg

typedef GPB_ENUM(KickOffLineMsg_FieldNumber) {
  KickOffLineMsg_FieldNumber_UserId = 1,
  KickOffLineMsg_FieldNumber_IdentityId = 2,
};

GPB_FINAL @interface KickOffLineMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *identityId;

@end

#pragma mark - EndSessionMsg

typedef GPB_ENUM(EndSessionMsg_FieldNumber) {
  EndSessionMsg_FieldNumber_SessionId = 1,
};

GPB_FINAL @interface EndSessionMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
